### ISSUE TITLE
404 for document getting from https://github.com/aitos-io/BoAT-X-Framework/tree/master/docs#readme

### ISSUE THREAD

**Issue by FengHuan1999** [aitos-io/BoAT-X-Framework#461]
**Is your feature request related to a problem? Please describe.**

Web return 404 when use get document from https://github.com/aitos-io/BoAT-X-Framework/tree/master/docs#readme
both for English Document & Chinese Document

**Describe the solution you'd like**

Where can I get the document of BoAT ? 
From this link or another link ? 

**Describe alternatives you've considered**

Remove this part refer another webpage and link 
or 
Make the right link here for document review

**Additional context**

**Comment by PanHH** [comment]
Some scripts were configured on github to dynamically generate docs website, which will convert markdown files into html pages only when the docs website is running. It returned 404 error pages because the markdown files you visited is not in a running state and the resources for the link will not be found. Please ignore this issue when viewing or editting markdown files.
The BoAT documentation website is available at https://aitos-io.github.io/BoAT-X-Framework.
